# Generated by Django 2.2 on 2022-04-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220324_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adminid',
            new_name='userid',
        ),
    ]
