# Generated by Django 2.2 on 2022-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_order_userorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='username',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(),
        ),
    ]
