# Generated by Django 2.2 on 2022-04-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_order_orderuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='outime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
