# Generated by Django 2.2 on 2022-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_userorder_outime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userstate',
            field=models.IntegerField(default=1),
        ),
    ]
